# Generated by Django 4.2.4 on 2023-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='arg_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='agreement amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='as_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='administrative sanction amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mait_charge',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='maintenance charge'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='Tender Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_exp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='Total Expenditure'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ts_amt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='technical sanction amount'),
        ),
    ]
