# Generated by Django 4.2.4 on 2023-10-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_project_arg_amt_alter_project_as_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_id', models.IntegerField(verbose_name='as_id')),
                ('as_awarded', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='as_awarded')),
                ('alc_fr_rki', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='allocation from rki')),
            ],
        ),
    ]
